#SLSA Demo Build 
name: CI

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  build:
    permissions: # Least privilege
      contents: read
      attestations: write
      id-token: write

    runs-on: ubuntu-latest # GitHub-hosted runner (isolated)
    
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 1  # SALSA recommends minimal history exposure

      - uses: actions/setup-node@v4
        with:
          node-version: 21.x
          check-latest: true
          cache: npm

      - name: Install dependencies
        run: npm install --ignore-scripts  # Enforce locked dependencies

      - name: Run tests
        run: npm test

      - name: Generate SBOM
        run: |
            npm install -g @cyclonedx/cyclonedx-npm
            # Verify package checksums using npm audit signatures
            npm audit signatures
            cyclonedx-npm --output-format json --output-file sbom.json

      - name: Generate Provenance Attestation
        uses: actions/attest-sbom@v1
        with:
          subject-path: src/index.js
          sbom-path: sbom.json
        
      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v4
        with:
          name: package
          path: |
            src/index.js
            sbom.json

  publish:
    if: ${{ github.ref == 'refs/heads/main' }}
    needs: build
    runs-on: ubuntu-latest
    permissions:
      contents: read
    
    steps:
      - name: Download Build Artifact
        uses: actions/download-artifact@v4
        with:
          name: package
          path: downloaded-package

      - name: Verify Integrity
        env:
          GH_TOKEN: ${{ github.token }}
        run: |
            gh attestation verify --owner wulfland --predicate-type https://cyclonedx.org/bom ./downloaded-package/src/index.js

      
